
FROM eclipse-temurin:17-jre-focal AS base
COPY --from=lankalana/libreoffice-headless:7.6.7.2-eclipse-temurin-17-jre-focal /libreoffice /usr/lib/libreoffice
# Install LibreOffice and its dependencies
RUN apt update \ 
	&& apt install -y --no-install-recommends \
		libcairo2 \
		libcups2 \
		libdbus-1-3 \
		libglib2.0-0 \
		libnss3 \
		libxinerama1 \
		libxml2 \
	&& apt clean \
	&& ln -s /usr/lib/libreoffice/program/soffice.bin /usr/bin/soffice