name: Build and publish docker container

on:
  workflow_dispatch:
    inputs:
      libre-office-version:
        description: 'LibreOffice version to build'
        required: true
        type: string

jobs:
  build-amd64:
    name: Build and publish amd64 version
    runs-on: ubuntu-24.04
    env:
      LIBRE_URL: https://downloadarchive.documentfoundation.org/libreoffice/old/${{inputs.libre-office-version}}/src/libreoffice-${{inputs.libre-office-version}}.tar.xz
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download source code
        run: wget $LIBRE_URL -O libre.tar.xz
      - name: Extract source code
        run: tar -xJf libre.tar.xz -C ./ --strip-components=1
      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install -y git build-essential zip ccache junit4 libkrb5-dev nasm graphviz python3 python3-dev python3-setuptools qtbase5-dev libkf5coreaddons-dev libkf5i18n-dev libkf5config-dev libkf5windowsystem-dev libkf5kio-dev libqt5x11extras5-dev autoconf libcups2-dev libfontconfig1-dev gperf libxslt1-dev xsltproc libxml2-utils libxrandr-dev libx11-dev bison flex libgtk-3-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev ant ant-optional libnss3-dev libavahi-client-dev libxt-dev
      - name: Generate config
        run: ./autogen.sh --disable-dependency-tracking --disable-gui --disable-gdb-index --disable-xmlhelp --without-java --disable-postgresql-sdbc --with-galleries=no --without-system-fontconfig --with-theme="breeze_dark" --enable-release-build --enable-lto --enable-optimized=yes --without-package-format
      - name: Build
        run: make
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}-amd64
          tags: |
            type=match,pattern=\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+\.\d+,value=${{inputs.libre-office-version}}
            type=raw,value=${{inputs.libre-office-version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.partial
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-arm64:
    name: Build and publish arm64 version
    runs-on: ubuntu-24.04-arm
    env:
      LIBRE_URL: https://downloadarchive.documentfoundation.org/libreoffice/old/${{inputs.libre-office-version}}/src/libreoffice-${{inputs.libre-office-version}}.tar.xz
    steps:
      - uses: actions/checkout@v4
      - name: Download source code
        run: wget $LIBRE_URL -O libre.tar.xz
      - name: Extract source code
        run: tar -xJf libre.tar.xz -C ./ --strip-components=1
      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install -y git build-essential zip ccache junit4 libkrb5-dev nasm graphviz python3 python3-dev python3-setuptools qtbase5-dev libkf5coreaddons-dev libkf5i18n-dev libkf5config-dev libkf5windowsystem-dev libkf5kio-dev libqt5x11extras5-dev autoconf libcups2-dev libfontconfig1-dev gperf libxslt1-dev xsltproc libxml2-utils libxrandr-dev libx11-dev bison flex libgtk-3-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev ant ant-optional libnss3-dev libavahi-client-dev libxt-dev
      - name: Generate config
        run: ./autogen.sh --disable-dependency-tracking --disable-gui --disable-gdb-index --disable-xmlhelp --without-java --disable-postgresql-sdbc --with-galleries=no --without-system-fontconfig --with-theme="breeze_dark" --enable-release-build --enable-lto --enable-optimized=yes --without-package-format
      - name: Build
        run: make
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}-arm64
          tags: |
            type=match,pattern=\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+\.\d+,value=${{inputs.libre-office-version}}
            type=raw,value=${{inputs.libre-office-version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.partial
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-docker-container:
    name: Build and publish merged docker container
    needs: [build-amd64, build-arm64]
    uses: ./.github/workflows/merge.yml
    with:
      image-version: ${{inputs.libre-office-version}}