name: Build and publish docker container

on:
  workflow_dispatch:
    inputs:
      libre-office-version:
        description: 'LibreOffice version to build'
        required: true
        type: string
      builder-image:
        description: 'Base image to use for building'
        required: true
        type: string
      image-version-suffix:
        description: 'Suffix to append to the image version'
        required: true

jobs:
  build-amd64:
    name: Build and publish amd64 version
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}-amd64
          tags: |
            type=match,pattern=\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+\.\d+,value=${{inputs.libre-office-version}}
            type=raw,value=${{inputs.libre-office-version}}
          flavor: suffix=-${{inputs.image-version-suffix}},onlatest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: Dockerfile.partial
          push: true
          build-args: |
            LIBRE_VERSION=${{inputs.libre-office-version}}
            BASE=${{inputs.builder-image}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-arm64:
    name: Build and publish arm64 version
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}-arm64
          tags: |
            type=match,pattern=\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+\.\d+,value=${{inputs.libre-office-version}}
            type=raw,value=${{inputs.libre-office-version}}
          flavor: suffix=-${{inputs.image-version-suffix}},onlatest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          file: Dockerfile.partial
          push: true
          build-args: |
            LIBRE_VERSION=${{inputs.libre-office-version}}
            BASE=${{inputs.builder-image}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-docker-container:
    name: Build and publish merged docker container
    needs: [build-amd64, build-arm64]
    uses: ./.github/workflows/merge.yml
    with:
      image-version: ${{inputs.libre-office-version}}-${{inputs.image-version-suffix}}
    secrets: inherit