name: Merge separate docker containers to a multiplatform image

on:
  workflow_dispatch:
    inputs:
      image-version:
        description: 'Container image versions to build'
        required: true
        type: string
  workflow_call:
    inputs:
      image-version:
        description: 'Container image versions to build'
        required: true
        type: string

jobs:
  build-docker-container:
    runs-on: ubuntu-latest
    name: Build and publish docker container
    needs: [build-amd64, build-arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=match,pattern=\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+,value=${{inputs.libre-office-version}}
            type=match,pattern=\d+\.\d+\.\d+,value=${{inputs.libre-office-version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
